# Makefile

CXXFLAGS := -std=c++11 -O0 -ggdb

# Note the \ \ denotes a singular line
PROGRAMS := lab6

.PHONY: all
all : $(PROGRAMS)

.PHONY: clean
clean :: -rm -f $(PROGRAMS) 
# The purpose of putting a dash next to any command line is to ignore any instances that don't exist 
# If error, ignore error and continue on

# Don't need
# -include instructor.mk
