# Makefile

# Note the \ \ denotes a singular line
PROGRAMS := \
	command-line-args \
	file-io-cc

CXXFLAGS := -std=c++11 -O0 -ggdb

.PHONY: all
all : $(PROGRAMS)

.PHONY: clean
clean : ; -rm -f $(PROGRAMS) 
# The purpose of putting a dash next to any command line is to ignore any instances that don't exist 
# If error, ignore error and continue on



